In [6]:
import cv2
import numpy as np

img = cv2.imread('car.png')
cv2.imshow('Car image',img) #'Car image' - заголовок окна, img - переменная, содержащая изображение

if img is not None:
    print(f"Ширина - {img.shape[0]} px, высота - {img.shape[1]} px, количество каналов: {img.shape[2]}")
    # print(f"Прочитано изображение размером {img.shape}")
else:
    print("Ошибка чтения изображения")

cv2.waitKey(0) #ожидает нажатия любой клавиши
cv2.destroyAllWindows() #закроет окно перед завершением скрипта


Ширина - 1024 px, высота - 1792 px, количество каналов: 3


In [7]:
import cv2
import numpy as np

# Загрузка исходного изображения
image = cv2.imread('car.png')

# Проверка, что изображение загружено
if image is None:
    print("Изображение не прочитано")
    exit()

red_channel = image[:, :, 2]  # Красный канал
green_channel = image[:, :, 1]  # Зеленый канал
blue_channel = image[:, :, 0]  # Синий канал

# Сохранение изображений
cv2.imwrite('red_channel.jpg', red_channel)
cv2.imwrite('green_channel.jpg', green_channel)
cv2.imwrite('blue_channel.jpg', blue_channel)

print("Images saved successfully.")

Images saved successfully.


In [34]:
import cv2
import numpy as np

image1 = cv2.imread("000.jpg")
image2 = cv2.imread("003.jpg")
image3 = cv2.imread("015.jpg")

if image1 is not None:
    print(f"Ширина - {image1.shape[0]} px, высота - {image1.shape[1]} px, количество каналов: {image1.shape[2]}")
    # print(f"Прочитано изображение размером {img.shape}")
else:
    print("Ошибка чтения изображения")

image1 = np.where(image1 < 10, 0, 255)
for i in range(image1.shape[0] // 2):
    for j in range(image1.shape[0] // 2):
        if image1[i][j].all() != 0:
            print(image1[i][j])


# cv2.imshow('000', np_image1)

cv2.waitKey(0) #ожидает нажатия любой клавиши
cv2.destroyAllWindows() #закроет окно перед завершением скрипта





Ширина - 50 px, высота - 50 px, количество каналов: 3
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255

In [8]:
image = cv2.imread('b.png')

red_channel = image[:, :, 2]  # Красный канал
green_channel = image[:, :, 1]  # Зеленый канал
blue_channel = image[:, :, 0]  # Синий канал

# if red_channel.mean() > green_channel.mean() and red_channel.mean() > blue_channel.mean():
#     print('красный')

# if green_channel.mean() > red_channel.mean() and green_channel.mean() > blue_channel.mean():
#     print('зелёный')

# if blue_channel.mean() > green_channel.mean() and blue_channel.mean() > red_channel.mean():
#     print('синий')


blue, green, red = np.sum(image[:, :, 0]), np.sum(image[:, :, 1]), np.sum(image[:, :, 2])
print([['синий', 'зелёный'][max(blue, green, red) == green], 'красный'][max(blue, green, red) == red])
# print(red_channel)
# print(green_channel)
# print(blue_channel)

синий


C:\Users\Admin\AppData\Local\Temp\ipykernel_10944\2062332675.py:18: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  print([['синий', 'зелёный'][max(blue, green, red) == green], 'красный'][max(blue, green, red) == red])


In [9]:
color = '[0 0 253]'
color = tuple([int(x) for x in (color[1:-1]).split()])

colors = {(255,255,255):"white",
          (0,0,255):"red",
          (0,255,0):"green",
          (255,0,0):"blue",
          (0,255,255):"yellow",
          (255,0,255):"purple",
          (255,255,0):"aqua",
          (0,0,0):"black"}

if color in colors:
    print(f'This {color} is {colors[color]}')